UPDATE `jobsinfo` SET `career_name`="Aerospace Engineering and Operations Technician" where id="17-3021.00";
UPDATE `jobsinfo` SET `career_name`="Aerospace Engineer" where id="17-2011.00";
UPDATE `jobsinfo` SET `career_name`="Agricultural Engineer" where id="17-2021.00";
UPDATE `jobsinfo` SET `career_name`="Architect" where id="17-1011.00";
UPDATE `jobsinfo` SET `career_name`="Biomedical Engineer" where id="17-2031.00";
UPDATE `jobsinfo` SET `career_name`="Cartographer" where id="17-1021.00";
UPDATE `jobsinfo` SET `career_name`="Chemical Engineer" where id="17-2041.00";
UPDATE `jobsinfo` SET `career_name`="Civil Engineer" where id="17-2051.00";
UPDATE `jobsinfo` SET `career_name`="Computer Hardware Engineer" where id="17-2061.00";
UPDATE `jobsinfo` SET `career_name`="Electrical Engineer" where id="17-2071.00";
UPDATE `jobsinfo` SET `career_name`="Environmental Engineer" where id="17-2081.00";
UPDATE `jobsinfo` SET `career_name`="Industrial Engineer" where id="17-2112.00";
UPDATE `jobsinfo` SET `career_name`="Landscape Architect" where id="17-1012.00";
UPDATE `jobsinfo` SET `career_name`="Marine Engineer" where id="17-2121.01";
UPDATE `jobsinfo` SET `career_name`="Mechanical Engineer" where id="17-2141.00";
UPDATE `jobsinfo` SET `career_name`="Nuclear Engineer" where id="17-2161.00";
UPDATE `jobsinfo` SET `career_name`="Advertising Art Director" where id="27-1011.00";
UPDATE `jobsinfo` SET `career_name`="Cartoonists" where id="27-1012.00";
UPDATE `jobsinfo` SET `career_name`="Floral Designer" where id="27-1023.00";
UPDATE `jobsinfo` SET `career_name`="Graphic Designer" where id="27-1024.00";
UPDATE `jobsinfo` SET `career_name`="Industrial Designer" where id="27-1021.00";
UPDATE `jobsinfo` SET `career_name`="Public Accountant" where id="13-2011.01";
UPDATE `jobsinfo` SET `career_name`="Budget Analyst" where id="13-2031.00";
UPDATE `jobsinfo` SET `career_name`="Claims Adjuster" where id="13-1031.01";
UPDATE `jobsinfo` SET `career_name`="Benefits Specialist" where id="13-1141.00";
UPDATE `jobsinfo` SET `career_name`="Financial Analyst" where id="13-2051.00";
UPDATE `jobsinfo` SET `career_name`="Financial Examiner" where id="13-2061.00";
UPDATE `jobsinfo` SET `career_name`="Insurance Underwriter" where id="13-2053.00";
UPDATE `jobsinfo` SET `career_name`="Loan Officer" where id="13-2072.00";
UPDATE `jobsinfo` SET `career_name`="Logistician" where id="13-1081.00";
UPDATE `jobsinfo` SET `career_name`="Management Analyst" where id="13-1111.00";
UPDATE `jobsinfo` SET `career_name`="Purchasing Manager" where id="11-3061.00";
UPDATE `jobsinfo` SET `career_name`="Revenue Officer" where id="13-2081.00";
UPDATE `jobsinfo` SET `career_name`="Training and Development Specialist" where id="13-1151.00";
UPDATE `jobsinfo` SET `career_name`="Health Educator" where id="21-1091.00";
UPDATE `jobsinfo` SET `career_name`="Career Counselor" where id="21-1012.00";
UPDATE `jobsinfo` SET `career_name`="Substance Abuse Social Workers" where id="21-1023.00";
UPDATE `jobsinfo` SET `career_name`="Child and Family Social Worker" where id="21-1021.00";
UPDATE `jobsinfo` SET `career_name`="Substance Abuse Counselor" where id="21-1011.00";
UPDATE `jobsinfo` SET `career_name`="Data scientist" where id="15-1111.00";
UPDATE `jobsinfo` SET `career_name`="Network Architect" where id="15-1143.00";
UPDATE `jobsinfo` SET `career_name`="Computer Programmer" where id="15-1131.00";
UPDATE `jobsinfo` SET `career_name`="Computer Systems Analyst" where id="15-1121.00";
UPDATE `jobsinfo` SET `career_name`="Database Administrator" where id="15-1141.00";
UPDATE `jobsinfo` SET `career_name`="Information Security Analyst" where id="15-1122.00";
UPDATE `jobsinfo` SET `career_name`="Network Administrator" where id="15-1142.00";
UPDATE `jobsinfo` SET `career_name`="Applications Software Developer" where id="15-1132.00";
UPDATE `jobsinfo` SET `career_name`="Systems Software Developers" where id="15-1133.00";
UPDATE `jobsinfo` SET `career_name`="Web Developer" where id="15-1134.00";
UPDATE `jobsinfo` SET `career_name`="Construction and Building Inspector" where id="47-4011.00";
UPDATE `jobsinfo` SET `career_name`="Construction Equipment Operator" where id="47-2073.00";
UPDATE `jobsinfo` SET `career_name`="Construction Laborer" where id="47-2061.00";
UPDATE `jobsinfo` SET `career_name`="Construction Painter" where id="47-2141.00";
UPDATE `jobsinfo` SET `career_name`="Solar Photovoltaic Installer" where id="47-2231.00";
UPDATE `jobsinfo` SET `career_name`="Archivist" where id="25-4011.00";
UPDATE `jobsinfo` SET `career_name`="Technical Education Teacher" where id="25-2023.00";
UPDATE `jobsinfo` SET `career_name`="Curator" where id="25-4012.00";
UPDATE `jobsinfo` SET `career_name`="Conservator" where id="25-4013.00";
UPDATE `jobsinfo` SET `career_name`="High School Teacher" where id="25-2031.00";
UPDATE `jobsinfo` SET `career_name`="Instructional Coordinator" where id="25-9031.00";
UPDATE `jobsinfo` SET `career_name`="Kindergarten Teacher" where id="25-2012.00";
UPDATE `jobsinfo` SET `career_name`="Elementary School Teacher" where id="25-2021.00";
UPDATE `jobsinfo` SET `career_name`="Librarian" where id="25-4021.00";
UPDATE `jobsinfo` SET `career_name`="Middle School Teacher" where id="25-2022.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Business Teacher" where id="25-1011.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Computer Science Teacher" where id="25-1021.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Mathematical Science Teacher" where id="25-1022.00";
UPDATE `jobsinfo` SET `career_name`="Architecture Teacher" where id="25-1031.00";
UPDATE `jobsinfo` SET `career_name`="Engineering Teacher" where id="25-1032.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Archeology Teachers" where id="25-1061.00";
UPDATE `jobsinfo` SET `career_name`="Area, Ethnic, and Cultural Studies Teacher" where id="25-1062.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Economics Teacher" where id="25-1063.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Geography Teacher" where id="25-1064.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Political Science Teacher" where id="25-1065.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Psychology Teacher" where id="25-1066.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Sociology Teacher" where id="25-1067.00";
UPDATE `jobsinfo` SET `career_name`="Health Specialties Teacher" where id="25-1071.00";
UPDATE `jobsinfo` SET `career_name`="Nursing Instructor" where id="25-1072.00";
UPDATE `jobsinfo` SET `career_name`="Education Teacher" where id="25-1081.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Library Science Teacher" where id="25-1082.00";
UPDATE `jobsinfo` SET `career_name`="Criminal Justice Teacher" where id="25-1111.00";
UPDATE `jobsinfo` SET `career_name`="Law Teacher" where id="25-1112.00";
UPDATE `jobsinfo` SET `career_name`="Social Work Teacher" where id="25-1113.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary English Language and Literature Teacher" where id="25-1123.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Foreign Language and Literature Teacher" where id="25-1124.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary History Teacher" where id="25-1125.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Philosophy Teacher" where id="25-1126.00";
UPDATE `jobsinfo` SET `career_name`="Paid Professional Athlete" where id="27-2021.00";
UPDATE `jobsinfo` SET `career_name`="Sports Coach" where id="27-2022.00";
UPDATE `jobsinfo` SET `career_name`="Dancer" where id="27-2031.00";
UPDATE `jobsinfo` SET `career_name`="Choreographer" where id="27-2032.00";
UPDATE `jobsinfo` SET `career_name`="Sports Referee" where id="27-2023.00";
UPDATE `jobsinfo` SET `career_name`="Animal Breeder" where id="45-2021.00";
UPDATE `jobsinfo` SET `career_name`="Waiter / Waitresse" where id="35-3031.00";
UPDATE `jobsinfo` SET `career_name`="Exercise Physiologist" where id="29-1128.00";
UPDATE `jobsinfo` SET `career_name`="Audiologist" where id="29-1181.00";
UPDATE `jobsinfo` SET `career_name`="Cardiovascular Technologist" where id="29-2031.00";
UPDATE `jobsinfo` SET `career_name`="Diagnostic Medical Sonographer" where id="29-2032.00";
UPDATE `jobsinfo` SET `career_name`="Nutritionist" where id="29-1031.00";
UPDATE `jobsinfo` SET `career_name`="Paramedic" where id="29-2041.00";
UPDATE `jobsinfo` SET `career_name`="Genetic Counselor" where id="29-9092.00";
UPDATE `jobsinfo` SET `career_name`="Clinical Laboratory Technician" where id="29-2012.00";
UPDATE `jobsinfo` SET `career_name`="Medical Assistant" where id="31-9092.00";
UPDATE `jobsinfo` SET `career_name`="Medical Transcriptionist" where id="31-9094.00";
UPDATE `jobsinfo` SET `career_name`="Health Information Technician" where id="29-2071.00";
UPDATE `jobsinfo` SET `career_name`="Nurse Anesthetist" where id="29-1151.00";
UPDATE `jobsinfo` SET `career_name`="Nurse Practitioner" where id="29-1171.00";
UPDATE `jobsinfo` SET `career_name`="Occupational Health and Safety Specialist" where id="29-9011.00";
UPDATE `jobsinfo` SET `career_name`="Occupational Therapist" where id="29-1122.00";
UPDATE `jobsinfo` SET `career_name`="Occupational Therapy Assistant" where id="31-2011.00";
UPDATE `jobsinfo` SET `career_name`="Dispensing Optician" where id="29-2081.00";
UPDATE `jobsinfo` SET `career_name`="Optometrist" where id="29-1041.00";
UPDATE `jobsinfo` SET `career_name`="Prosthetist" where id="29-2091.00";
UPDATE `jobsinfo` SET `career_name`="Pharmacist" where id="29-1051.00";
UPDATE `jobsinfo` SET `career_name`="Physician Assistant" where id="29-1071.00";
UPDATE `jobsinfo` SET `career_name`="Surgeon" where id="29-1067.00";
UPDATE `jobsinfo` SET `career_name`="Podiatrist" where id="29-1081.00";
UPDATE `jobsinfo` SET `career_name`="Psychiatric Aide" where id="31-1013.00";
UPDATE `jobsinfo` SET `career_name`="Radiation Therapist" where id="29-1124.00";
UPDATE `jobsinfo` SET `career_name`="Magnetic Resonance Imaging Technologist" where id="29-2035.00";
UPDATE `jobsinfo` SET `career_name`="Recreational Therapist" where id="29-1125.00";
UPDATE `jobsinfo` SET `career_name`="Registered Nurse" where id="29-1141.00";
UPDATE `jobsinfo` SET `career_name`="Respiratory Therapist" where id="29-1126.00";
UPDATE `jobsinfo` SET `career_name`="Surgical Technologist" where id="29-2055.00";
UPDATE `jobsinfo` SET `career_name`="Avionics Technician" where id="49-2091.00";
UPDATE `jobsinfo` SET `career_name`="Aircraft Mechanic" where id="49-3011.00";
UPDATE `jobsinfo` SET `career_name`="Automotive Repairer" where id="49-3021.00";
UPDATE `jobsinfo` SET `career_name`="Automotive Master Mechanic" where id="49-3023.01";
UPDATE `jobsinfo` SET `career_name`="Automotive Specialty Technician" where id="49-3023.02";
UPDATE `jobsinfo` SET `career_name`="Computer and Office Machine Repairer" where id="49-2011.00";
UPDATE `jobsinfo` SET `career_name`="Motorcycle Mechanic" where id="49-3052.00";
UPDATE `jobsinfo` SET `career_name`="Mediator" where id="23-1022.00";
UPDATE `jobsinfo` SET `career_name`="Court Reporter" where id="23-2091.00";
UPDATE `jobsinfo` SET `career_name`="Judge" where id="23-1021.00";
UPDATE `jobsinfo` SET `career_name`="Hearing Officer" where id="23-1023.00";
UPDATE `jobsinfo` SET `career_name`="Lawyer" where id="23-1011.00";
UPDATE `jobsinfo` SET `career_name`="Paralegal" where id="23-2011.00";
UPDATE `jobsinfo` SET `career_name`="Food Science Technician" where id="19-4011.02";
UPDATE `jobsinfo` SET `career_name`="Animal Scientist" where id="19-1011.00";
UPDATE `jobsinfo` SET `career_name`="Soil and Plant Scientist" where id="19-1013.00";
UPDATE `jobsinfo` SET `career_name`="Anthropologist" where id="19-3091.01";
UPDATE `jobsinfo` SET `career_name`="Archeologist" where id="19-3091.02";
UPDATE `jobsinfo` SET `career_name`="Atmospheric and Space Scientist" where id="19-2021.00";
UPDATE `jobsinfo` SET `career_name`="Biochemist" where id="19-1021.00";
UPDATE `jobsinfo` SET `career_name`="Biological Technician" where id="19-4021.00";
UPDATE `jobsinfo` SET `career_name`="Chemical Technician" where id="19-4031.00";
UPDATE `jobsinfo` SET `career_name`="Chemist" where id="19-2031.00";
UPDATE `jobsinfo` SET `career_name`="Materials Scientist" where id="19-2032.00";
UPDATE `jobsinfo` SET `career_name`="Conservation Scientist" where id="19-1031.01";
UPDATE `jobsinfo` SET `career_name`="Economist" where id="19-3011.00";
UPDATE `jobsinfo` SET `career_name`="Environmental Science Technician" where id="19-4091.00";
UPDATE `jobsinfo` SET `career_name`="Epidemiologist" where id="19-1041.00";
UPDATE `jobsinfo` SET `career_name`="Geographer" where id="19-3092.00";
UPDATE `jobsinfo` SET `career_name`="Geologist" where id="19-2042.00";
UPDATE `jobsinfo` SET `career_name`="Historian" where id="19-3093.00";
UPDATE `jobsinfo` SET `career_name`="Hydrologist" where id="19-2043.00";
UPDATE `jobsinfo` SET `career_name`="Cancer Researcher" where id="19-1042.00";
UPDATE `jobsinfo` SET `career_name`="Astronomer" where id="19-2011.00";
UPDATE `jobsinfo` SET `career_name`="Political Scientist" where id="19-3094.00";
UPDATE `jobsinfo` SET `career_name`="Clinical Psychologist" where id="19-3031.02";
UPDATE `jobsinfo` SET `career_name`="Counseling Psychologist" where id="19-3031.03";
UPDATE `jobsinfo` SET `career_name`="Industrial-Organizational Psychologist" where id="19-3032.00";
UPDATE `jobsinfo` SET `career_name`="Administrative Services Manager" where id="11-3011.00";
UPDATE `jobsinfo` SET `career_name`="Advertising and Promotions Manager" where id="11-2011.00";
UPDATE `jobsinfo` SET `career_name`="Marketing Manager" where id="11-2021.00";
UPDATE `jobsinfo` SET `career_name`="Architectural Manager" where id="11-9041.00";
UPDATE `jobsinfo` SET `career_name`="Compensation Manager" where id="11-3111.00";
UPDATE `jobsinfo` SET `career_name`="Computer and Information Systems Manager" where id="11-3021.00";
UPDATE `jobsinfo` SET `career_name`="Financial Controller" where id="11-3031.01";
UPDATE `jobsinfo` SET `career_name`="Academic Dean" where id="11-9033.00";
UPDATE `jobsinfo` SET `career_name`="Real Estate Manager" where id="11-9141.00";
UPDATE `jobsinfo` SET `career_name`="Public Relations Manager" where id="11-2031.00";
UPDATE `jobsinfo` SET `career_name`="Sales Manager" where id="11-2022.00";
UPDATE `jobsinfo` SET `career_name`="Chief executive" where id="11-1011.00";
UPDATE `jobsinfo` SET `career_name`="Statistician" where id="15-2041.00";
UPDATE `jobsinfo` SET `career_name`="Talk Show Host" where id="27-3011.00";
UPDATE `jobsinfo` SET `career_name`="Interpreter" where id="27-3091.00";
UPDATE `jobsinfo` SET `career_name`="Photographer" where id="27-4021.00";
UPDATE `jobsinfo` SET `career_name`="Public Relations Specialist" where id="27-3031.00";
UPDATE `jobsinfo` SET `career_name`="Writer" where id="27-3043.04";
UPDATE `jobsinfo` SET `career_name`="Credit Authorizer" where id="43-4041.01";
UPDATE `jobsinfo` SET `career_name`="Loan Interviewer" where id="43-4131.00";
UPDATE `jobsinfo` SET `career_name`="Insurance Claims Clerk" where id="43-9041.01";
UPDATE `jobsinfo` SET `career_name`="Court Clerk" where id="43-4031.01";
UPDATE `jobsinfo` SET `career_name`="Eligibility Interviewer" where id="43-4061.00";
UPDATE `jobsinfo` SET `career_name`="Hotel Clerk" where id="43-4081.00";
UPDATE `jobsinfo` SET `career_name`="Interviewer" where id="43-4111.00";
UPDATE `jobsinfo` SET `career_name`="Shipping, Receiving, and Traffic Clerk" where id="43-5071.00";
UPDATE `jobsinfo` SET `career_name`="Police, Fire, and Ambulance Dispatcher" where id="43-5031.00";
UPDATE `jobsinfo` SET `career_name`="Postal Service Clerk" where id="43-5051.00";
UPDATE `jobsinfo` SET `career_name`="Administrative Assistant" where id="43-6014.00";
UPDATE `jobsinfo` SET `career_name`="Barber" where id="39-5011.00";
UPDATE `jobsinfo` SET `career_name`="Fitness Trainer" where id="39-9031.00";
UPDATE `jobsinfo` SET `career_name`="Funeral Director" where id="39-4031.00";
UPDATE `jobsinfo` SET `career_name`="Mortician" where id="11-9061.00";
UPDATE `jobsinfo` SET `career_name`="Aircraft Structure Assembler" where id="51-2011.00";
UPDATE `jobsinfo` SET `career_name`="Electronic Equipment Assembler" where id="51-2022.00";
UPDATE `jobsinfo` SET `career_name`="Electromechanical Equipment Assembler" where id="51-2023.00";
UPDATE `jobsinfo` SET `career_name`="Baker" where id="51-3011.00";
UPDATE `jobsinfo` SET `career_name`="Butcher" where id="51-3021.00";
UPDATE `jobsinfo` SET `career_name`="Jeweler" where id="51-9071.01";
UPDATE `jobsinfo` SET `career_name`="Nuclear Power Reactor Operator" where id="51-8011.00";
UPDATE `jobsinfo` SET `career_name`="Power Plant Operator" where id="51-8013.00";
UPDATE `jobsinfo` SET `career_name`="Printing Worker" where id="51-5111.00";
UPDATE `jobsinfo` SET `career_name`="Quality Control Inspector" where id="51-9061.00";
UPDATE `jobsinfo` SET `career_name`="Semiconductor Processor" where id="51-9141.00";
UPDATE `jobsinfo` SET `career_name`="Water treatment plant and system operator" where id="51-8031.00";
UPDATE `jobsinfo` SET `career_name`="Firefighter" where id="33-2011.01";
UPDATE `jobsinfo` SET `career_name`="Fire Inspector" where id="33-2021.01";
UPDATE `jobsinfo` SET `career_name`="Police Detective" where id="33-3021.01";
UPDATE `jobsinfo` SET `career_name`="Advertising Sales Agent" where id="41-3011.00";
UPDATE `jobsinfo` SET `career_name`="Insurance Sales Agent" where id="41-3021.00";
UPDATE `jobsinfo` SET `career_name`="Model" where id="41-9012.00";
UPDATE `jobsinfo` SET `career_name`="Real Estate Broker" where id="41-9021.00";
UPDATE `jobsinfo` SET `career_name`="Sales Engineer" where id="41-9031.00";
UPDATE `jobsinfo` SET `career_name`="Securities and Commodities Sales Agent" where id="41-3031.01";
UPDATE `jobsinfo` SET `career_name`="Financial Services Sales Agent" where id="41-3031.02";
UPDATE `jobsinfo` SET `career_name`="Wholesale and Manufacturing sales Representative" where id="41-4011.00";
UPDATE `jobsinfo` SET `career_name`="Airline Pilot" where id="53-2011.00";
UPDATE `jobsinfo` SET `career_name`="Air Traffic Controller" where id="53-2021.00";
UPDATE `jobsinfo` SET `career_name`="Yardmaster" where id="53-4031.00";
UPDATE `jobsinfo` SET `career_name`="Chauffeur" where id="53-3041.00";
UPDATE `jobsinfo` SET `career_name`="Sailor" where id="53-5011.00";
UPDATE `jobsinfo` SET `career_name`="Boat Captain" where id="53-5021.01";
UPDATE `jobsinfo` SET `career_name`="Ship Pilot" where id="53-5021.03";
UPDATE `jobsinfo` SET `career_name`="Motorboat Operator" where id="53-5022.00";
UPDATE `jobsinfo` SET `career_name`="Ship Engineer" where id="53-5031.00";
UPDATE `jobsinfo` SET `career_name`="Architectural Drafter" where id="17-3011.01";
UPDATE `jobsinfo` SET `career_name`="Electronics Engineering Technician" where id="17-3023.01";
UPDATE `jobsinfo` SET `career_name`="Electrical Engineering Technician" where id="17-3023.03";
UPDATE `jobsinfo` SET `career_name`="Electronics Engineer" where id="17-2072.00";
UPDATE `jobsinfo` SET `career_name`="Electro-Mechanical Technician" where id="17-3024.00";
UPDATE `jobsinfo` SET `career_name`="Environmental Engineering Technician" where id="17-3025.00";
UPDATE `jobsinfo` SET `career_name`="Industrial Engineering Technician" where id="17-3026.00";
UPDATE `jobsinfo` SET `career_name`="Materials Engineer" where id="17-2131.00";
UPDATE `jobsinfo` SET `career_name`="Mechanical Engineering Technician" where id="17-3027.00";
UPDATE `jobsinfo` SET `career_name`="Geological Engineer" where id="17-2151.00";
UPDATE `jobsinfo` SET `career_name`="Petroleum Engineer" where id="17-2171.00";
UPDATE `jobsinfo` SET `career_name`="Surveying Technician" where id="17-3031.01";
UPDATE `jobsinfo` SET `career_name`="Mapping Technician" where id="17-3031.02";
UPDATE `jobsinfo` SET `career_name`="Surveyor" where id="17-1022.00";
UPDATE `jobsinfo` SET `career_name`="Painter" where id="27-1013.00";
UPDATE `jobsinfo` SET `career_name`="Fashion Designer" where id="27-1022.00";
UPDATE `jobsinfo` SET `career_name`="Interior Designer" where id="27-1025.00";
UPDATE `jobsinfo` SET `career_name`="Multimedia Artist" where id="27-1014.00";
UPDATE `jobsinfo` SET `career_name`="Janitor" where id="37-2011.00";
UPDATE `jobsinfo` SET `career_name`="Housekeeping Cleaner" where id="37-2012.00";
UPDATE `jobsinfo` SET `career_name`="Pest Control Worker" where id="37-2021.00";
UPDATE `jobsinfo` SET `career_name`="Assessor of Real Estate" where id="13-2021.01";
UPDATE `jobsinfo` SET `career_name`="Manufacturing Cost Estimator" where id="13-1051.00";
UPDATE `jobsinfo` SET `career_name`="Events Fundraiser" where id="13-1131.00";
UPDATE `jobsinfo` SET `career_name`="Employment interviewer" where id="13-1071.00";
UPDATE `jobsinfo` SET `career_name`="Market Research Analyst" where id="13-1161.00";
UPDATE `jobsinfo` SET `career_name`="Event Planner" where id="13-1121.00";
UPDATE `jobsinfo` SET `career_name`="Personal Financial Advisor" where id="13-2052.00";
UPDATE `jobsinfo` SET `career_name`="Purchasing Agent of Farm Products" where id="13-1021.00";
UPDATE `jobsinfo` SET `career_name`="Community Health Worker" where id="21-1094.00";
UPDATE `jobsinfo` SET `career_name`="Marriage and Family Therapist" where id="21-1013.00";
UPDATE `jobsinfo` SET `career_name`="Mental Health Counselor" where id="21-1014.00";
UPDATE `jobsinfo` SET `career_name`="Probation Officer" where id="21-1092.00";
UPDATE `jobsinfo` SET `career_name`="Rehabilitation Counselor" where id="21-1015.00";
UPDATE `jobsinfo` SET `career_name`="Social Service Assistant" where id="21-1093.00";
UPDATE `jobsinfo` SET `career_name`="Healthcare Social Worker" where id="21-1022.00";
UPDATE `jobsinfo` SET `career_name`="Computer User Support Specialist" where id="15-1151.00";
UPDATE `jobsinfo` SET `career_name`="Computer Network Support Specialist" where id="15-1152.00";
UPDATE `jobsinfo` SET `career_name`="Boilermaker" where id="47-2011.00";
UPDATE `jobsinfo` SET `career_name`="Brickmason" where id="47-2021.00";
UPDATE `jobsinfo` SET `career_name`="Stonemason" where id="47-2022.00";
UPDATE `jobsinfo` SET `career_name`="Residential Carpenters" where id="47-2031.01";
UPDATE `jobsinfo` SET `career_name`="Commercial Carpenter" where id="47-2031.02";
UPDATE `jobsinfo` SET `career_name`="Cement Mason" where id="47-2051.00";
UPDATE `jobsinfo` SET `career_name`="Terrazzo Worker" where id="47-2053.00";
UPDATE `jobsinfo` SET `career_name`="Drywall and Ceiling Tile Installer" where id="47-2081.00";
UPDATE `jobsinfo` SET `career_name`="Taper" where id="47-2082.00";
UPDATE `jobsinfo` SET `career_name`="Electrician" where id="47-2111.00";
UPDATE `jobsinfo` SET `career_name`="Elevator Installer and Repairer" where id="47-4021.00";
UPDATE `jobsinfo` SET `career_name`="Glazier" where id="47-2121.00";
UPDATE `jobsinfo` SET `career_name`="Hazardous Materials Removal Worker" where id="47-4041.00";
UPDATE `jobsinfo` SET `career_name`="Insulation Worker" where id="47-2131.00";
UPDATE `jobsinfo` SET `career_name`="Pipe Fitter" where id="47-2152.01";
UPDATE `jobsinfo` SET `career_name`="Plumber" where id="47-2152.02";
UPDATE `jobsinfo` SET `career_name`="Roofer" where id="47-2181.00";
UPDATE `jobsinfo` SET `career_name`="Sheet Metal Worker" where id="47-2211.00";
UPDATE `jobsinfo` SET `career_name`="Structural Iron and Steel Worker" where id="47-2221.00";
UPDATE `jobsinfo` SET `career_name`="Tile and Marble Setter" where id="47-2044.00";
UPDATE `jobsinfo` SET `career_name`="Library Technician" where id="25-4031.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Agricultural Sciences Teacher" where id="25-1041.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Biological Science Teacher" where id="25-1042.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Forestry and Conservation Science Teacher" where id="25-1043.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Atmospheric, Earth, Marine, and Space Sciences Teacher" where id="25-1051.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Chemistry Teachers" where id="25-1052.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Environmental Science Teacher" where id="25-1053.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Physics Teacher" where id="25-1054.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Art, Drama, and Music Teacher" where id="25-1121.00";
UPDATE `jobsinfo` SET `career_name`="Postsecondary Communications Teacher" where id="25-1122.00";
UPDATE `jobsinfo` SET `career_name`="Preschool Teacher" where id="25-2011.00";
UPDATE `jobsinfo` SET `career_name`="Special Education Teacher" where id="25-2053.00";
UPDATE `jobsinfo` SET `career_name`="Teacher Assistant" where id="25-9041.00";
UPDATE `jobsinfo` SET `career_name`="Actor" where id="27-2011.00";
UPDATE `jobsinfo` SET `career_name`="Music Director" where id="27-2041.01";
UPDATE `jobsinfo` SET `career_name`="Music Composer" where id="27-2041.04";
UPDATE `jobsinfo` SET `career_name`="Singer" where id="27-2042.01";
UPDATE `jobsinfo` SET `career_name`="Musician" where id="27-2042.02";
UPDATE `jobsinfo` SET `career_name`="Producer" where id="27-2012.01";
UPDATE `jobsinfo` SET `career_name`="Agricultural Equipment Operator" where id="45-2091.00";
UPDATE `jobsinfo` SET `career_name`="Nursery Worker" where id="45-2092.01";
UPDATE `jobsinfo` SET `career_name`="Farmworker" where id="45-2093.00";
UPDATE `jobsinfo` SET `career_name`="Fish and Game Warden" where id="33-3031.00";
UPDATE `jobsinfo` SET `career_name`="Fishing Boat Captain" where id="45-3011.00";
UPDATE `jobsinfo` SET `career_name`="Forest and Conservation Worker" where id="45-4011.00";
UPDATE `jobsinfo` SET `career_name`="Faller" where id="45-4021.00";
UPDATE `jobsinfo` SET `career_name`="Logging Equipment Operator" where id="45-4022.00";
UPDATE `jobsinfo` SET `career_name`="Log Grader" where id="45-4023.00";
UPDATE `jobsinfo` SET `career_name`="Bartender" where id="35-3011.00";
UPDATE `jobsinfo` SET `career_name`="Chef" where id="35-1011.00";
UPDATE `jobsinfo` SET `career_name`="Food and Beverage Serving Worker" where id="35-3021.00";
UPDATE `jobsinfo` SET `career_name`="Food Preparation Worker" where id="35-2021.00";
UPDATE `jobsinfo` SET `career_name`="Athletic Trainer" where id="29-9091.00";
UPDATE `jobsinfo` SET `career_name`="Chiropractor" where id="29-1011.00";
UPDATE `jobsinfo` SET `career_name`="Dental Assistant" where id="31-9091.00";
UPDATE `jobsinfo` SET `career_name`="Dental Hygienist" where id="29-2021.00";
UPDATE `jobsinfo` SET `career_name`="Dentist" where id="29-1021.00";
UPDATE `jobsinfo` SET `career_name`="Oral and Maxillofacial Surgeon" where id="29-1022.00";
UPDATE `jobsinfo` SET `career_name`="Orthodontist" where id="29-1023.00";
UPDATE `jobsinfo` SET `career_name`="Home Health Aide" where id="31-1011.00";
UPDATE `jobsinfo` SET `career_name`="Licensed Vocational Nurse" where id="29-2061.00";
UPDATE `jobsinfo` SET `career_name`="Massage Therapist" where id="31-9011.00";
UPDATE `jobsinfo` SET `career_name`="Clinical Laboratory Technologist" where id="29-2011.00";
UPDATE `jobsinfo` SET `career_name`="Nuclear Medicine Technologist" where id="29-2033.00";
UPDATE `jobsinfo` SET `career_name`="Nurse Midwive" where id="29-1161.00";
UPDATE `jobsinfo` SET `career_name`="Nursing Assistant" where id="31-1014.00";
UPDATE `jobsinfo` SET `career_name`="Occupational Health and Safety Technician" where id="29-9012.00";
UPDATE `jobsinfo` SET `career_name`="Occupational Therapy Aide" where id="31-2012.00";
UPDATE `jobsinfo` SET `career_name`="Personal Care Aide" where id="39-9021.00";
UPDATE `jobsinfo` SET `career_name`="Pharmacy Technician" where id="29-2052.00";
UPDATE `jobsinfo` SET `career_name`="Phlebotomist" where id="31-9097.00";
UPDATE `jobsinfo` SET `career_name`="Physical Therapist Assistant" where id="31-2021.00";
UPDATE `jobsinfo` SET `career_name`="Physical Therapist" where id="29-1123.00";
UPDATE `jobsinfo` SET `career_name`="Psychiatric Technician" where id="29-2053.00";
UPDATE `jobsinfo` SET `career_name`="Radiologic Technologist" where id="29-2034.00";
UPDATE `jobsinfo` SET `career_name`="Speech-Language Pathologist" where id="29-1127.00";
UPDATE `jobsinfo` SET `career_name`="Veterinarian" where id="29-1131.00";
UPDATE `jobsinfo` SET `career_name`="Laboratory Animal Caretaker" where id="31-9096.00";
UPDATE `jobsinfo` SET `career_name`="Veterinary Technologist" where id="29-2056.00";
UPDATE `jobsinfo` SET `career_name`="Bus and Truck Mechanic" where id="49-3031.00";
UPDATE `jobsinfo` SET `career_name`="Electric Motor Repairer" where id="49-2092.00";
UPDATE `jobsinfo` SET `career_name`="Farm Equipment Mechanic" where id="49-3041.00";
UPDATE `jobsinfo` SET `career_name`="Rail Car Repairer" where id="49-3043.00";
UPDATE `jobsinfo` SET `career_name`="Industrial Machinery Maintenance Worker" where id="49-9043.00";
UPDATE `jobsinfo` SET `career_name`="Millwright" where id="49-9044.00";
UPDATE `jobsinfo` SET `career_name`="Electrical Power-Line Installer" where id="49-9051.00";
UPDATE `jobsinfo` SET `career_name`="Medical Equipment Repairer" where id="49-9062.00";
UPDATE `jobsinfo` SET `career_name`="Motorboat Mechanic" where id="49-3051.00";
UPDATE `jobsinfo` SET `career_name`="Telecommunications Equipment Installer" where id="49-2022.00";
UPDATE `jobsinfo` SET `career_name`="Wind Turbine Service Technician" where id="49-9081.00";
UPDATE `jobsinfo` SET `career_name`="Agricultural Technician" where id="19-4011.01";
UPDATE `jobsinfo` SET `career_name`="Food Science Technician" where id="19-1012.00";
UPDATE `jobsinfo` SET `career_name`="Forester" where id="19-1032.00";
UPDATE `jobsinfo` SET `career_name`="Environmental Scientist" where id="19-2041.00";
UPDATE `jobsinfo` SET `career_name`="Forensic Science Technician" where id="19-4092.00";
UPDATE `jobsinfo` SET `career_name`="Forest Technician" where id="19-4093.00";
UPDATE `jobsinfo` SET `career_name`="Geological Technician" where id="19-4041.01";
UPDATE `jobsinfo` SET `career_name`="Microbiologist" where id="19-1022.00";
UPDATE `jobsinfo` SET `career_name`="Nuclear Technician" where id="19-4051.01";
UPDATE `jobsinfo` SET `career_name`="Physicist" where id="19-2012.00";
UPDATE `jobsinfo` SET `career_name`="School Psychologist" where id="19-3031.01";
UPDATE `jobsinfo` SET `career_name`="Sociologist" where id="19-3041.00";
UPDATE `jobsinfo` SET `career_name`="Survey Researcher" where id="19-3022.00";
UPDATE `jobsinfo` SET `career_name`="Urban Planner" where id="19-3051.00";
UPDATE `jobsinfo` SET `career_name`="Zoologist" where id="19-1023.00";
UPDATE `jobsinfo` SET `career_name`="Construction Manager" where id="11-9021.00";
UPDATE `jobsinfo` SET `career_name`="High School Principal" where id="11-9032.00";
UPDATE `jobsinfo` SET `career_name`="Emergency Management Director" where id="11-9161.00";
UPDATE `jobsinfo` SET `career_name`="Agricultural Manager" where id="11-9013.01";
UPDATE `jobsinfo` SET `career_name`="Food Service Manager" where id="11-9051.00";
UPDATE `jobsinfo` SET `career_name`="Human Resources Manager" where id="11-3121.00";
UPDATE `jobsinfo` SET `career_name`="Industrial Production Manager" where id="11-3051.00";
UPDATE `jobsinfo` SET `career_name`="Convention Service Manager" where id="11-9081.00";
UPDATE `jobsinfo` SET `career_name`="Clinical Manager" where id="11-9111.00";
UPDATE `jobsinfo` SET `career_name`="Natural Sciences Manager" where id="11-9121.00";
UPDATE `jobsinfo` SET `career_name`="Childcare Center Director" where id="11-9031.00";
UPDATE `jobsinfo` SET `career_name`="Social and Community Service Manager" where id="11-9151.00";
UPDATE `jobsinfo` SET `career_name`="Training and Development Manager" where id="11-3131.00";
UPDATE `jobsinfo` SET `career_name`="Actuary" where id="15-2011.00";
UPDATE `jobsinfo` SET `career_name`="Mathematician" where id="15-2021.00";
UPDATE `jobsinfo` SET `career_name`="Operations Research Analyst" where id="15-2031.00";
UPDATE `jobsinfo` SET `career_name`="Broadcast Technician" where id="27-4012.00";
UPDATE `jobsinfo` SET `career_name`="Radio Operator" where id="27-4013.00";
UPDATE `jobsinfo` SET `career_name`="Sound Engineering Technician" where id="27-4014.00";
UPDATE `jobsinfo` SET `career_name`="Editor" where id="27-3041.00";
UPDATE `jobsinfo` SET `career_name`="Camera Operator" where id="27-4031.00";
UPDATE `jobsinfo` SET `career_name`="Film and Video Editor" where id="27-4032.00";
UPDATE `jobsinfo` SET `career_name`="News Analyst" where id="27-3021.00";
UPDATE `jobsinfo` SET `career_name`="Reporter" where id="27-3022.00";
UPDATE `jobsinfo` SET `career_name`="Technical Writer" where id="27-3042.00";
UPDATE `jobsinfo` SET `career_name`="Bill and Account Collector" where id="43-3011.00";
UPDATE `jobsinfo` SET `career_name`="Bookkeeping, Accounting, and Auditing Clerk" where id="43-3031.00";
UPDATE `jobsinfo` SET `career_name`="Customer Service Representative" where id="43-4051.00";
UPDATE `jobsinfo` SET `career_name`="Desktop Publisher" where id="43-9031.00";
UPDATE `jobsinfo` SET `career_name`="Brokerage Clerk" where id="43-4011.00";
UPDATE `jobsinfo` SET `career_name`="Credit Checker" where id="43-4041.02";
UPDATE `jobsinfo` SET `career_name`="General Office Clerk" where id="43-9061.00";
UPDATE `jobsinfo` SET `career_name`="Correspondence Clerk" where id="43-4021.00";
UPDATE `jobsinfo` SET `career_name`="File Clerk" where id="43-4071.00";
UPDATE `jobsinfo` SET `career_name`="Production, Planning, and Expediting Clerk" where id="43-5061.00";
UPDATE `jobsinfo` SET `career_name`="Payroll and Timekeeping Clerk" where id="43-3051.00";
UPDATE `jobsinfo` SET `career_name`="Procurement Clerk" where id="43-3061.00";
UPDATE `jobsinfo` SET `career_name`="Postal Service Mail Carrier" where id="43-5052.00";
UPDATE `jobsinfo` SET `career_name`="Postal Service Mail Processing Machine Operator" where id="43-5053.00";
UPDATE `jobsinfo` SET `career_name`="Executive Secretary" where id="43-6011.00";
UPDATE `jobsinfo` SET `career_name`="Legal Secretary" where id="43-6012.00";
UPDATE `jobsinfo` SET `career_name`="Medical Secretary" where id="43-6013.00";
UPDATE `jobsinfo` SET `career_name`="Teller" where id="43-3071.00";
UPDATE `jobsinfo` SET `career_name`="Animal Trainer" where id="39-2011.00";
UPDATE `jobsinfo` SET `career_name`="Nonfarm Animal Caretaker" where id="39-2021.00";
UPDATE `jobsinfo` SET `career_name`="Hairdresser" where id="39-5012.00";
UPDATE `jobsinfo` SET `career_name`="Childcare Worker" where id="39-9011.00";
UPDATE `jobsinfo` SET `career_name`="Funeral Attendant" where id="39-4021.00";
UPDATE `jobsinfo` SET `career_name`="Gaming Supervisor" where id="39-1011.00";
UPDATE `jobsinfo` SET `career_name`="Slot Supervisor" where id="39-1012.00";
UPDATE `jobsinfo` SET `career_name`="Gaming Dealer" where id="39-3011.00";
UPDATE `jobsinfo` SET `career_name`="Manicurist" where id="39-5092.00";
UPDATE `jobsinfo` SET `career_name`="Recreation Worker" where id="39-9032.00";
UPDATE `jobsinfo` SET `career_name`="Skincare Specialist" where id="39-5094.00";
UPDATE `jobsinfo` SET `career_name`="Engine Assembler" where id="51-2031.00";
UPDATE `jobsinfo` SET `career_name`="Structural Metal Fabricator" where id="51-2041.00";
UPDATE `jobsinfo` SET `career_name`="Fiberglass Fabricator" where id="51-2091.00";
UPDATE `jobsinfo` SET `career_name`="Dental Laboratory Technician" where id="51-9081.00";
UPDATE `jobsinfo` SET `career_name`="Ophthalmic Laboratory Technician" where id="51-9083.00";
UPDATE `jobsinfo` SET `career_name`="Food and Tobacco Processing Worker" where id="51-3091.00";
UPDATE `jobsinfo` SET `career_name`="Food Batchmaker" where id="51-3092.00";
UPDATE `jobsinfo` SET `career_name`="Food Cooking Machine Operator" where id="51-3093.00";
UPDATE `jobsinfo` SET `career_name`="Precious Metal Worker" where id="51-9071.07";
UPDATE `jobsinfo` SET `career_name`="Laundry and Dry-Cleaning Worker" where id="51-6011.00";
UPDATE `jobsinfo` SET `career_name`="Tool and Die Maker" where id="51-4111.00";
UPDATE `jobsinfo` SET `career_name`="Metal and Plastic Machine Worker" where id="51-4021.00";
UPDATE `jobsinfo` SET `career_name`="Meat Packer" where id="51-3023.00";
UPDATE `jobsinfo` SET `career_name`="Welder" where id="51-4121.06";
UPDATE `jobsinfo` SET `career_name`="Solderer" where id="51-4121.07";
UPDATE `jobsinfo` SET `career_name`="Furniture Finisher" where id="51-7021.00";
UPDATE `jobsinfo` SET `career_name`="Correctional Officer" where id="33-3012.00";
UPDATE `jobsinfo` SET `career_name`="Fire Investigator" where id="33-2021.02";
UPDATE `jobsinfo` SET `career_name`="Private Detective" where id="33-9021.00";
UPDATE `jobsinfo` SET `career_name`="Gaming Surveillance Officer" where id="33-9031.00";
UPDATE `jobsinfo` SET `career_name`="Security Guard" where id="33-9032.00";
UPDATE `jobsinfo` SET `career_name`="Cashier" where id="41-2011.00";
UPDATE `jobsinfo` SET `career_name`="Real Estate Sales Agent" where id="41-9022.00";
UPDATE `jobsinfo` SET `career_name`="Travel Agent" where id="41-3041.00";
UPDATE `jobsinfo` SET `career_name`="Bus Driver" where id="53-3021.00";
UPDATE `jobsinfo` SET `career_name`="Delivery Services Driver" where id="53-3033.00";
UPDATE `jobsinfo` SET `career_name`="Flight Attendant" where id="53-2031.00";
UPDATE `jobsinfo` SET `career_name`="Locomotive Engineer" where id="53-4011.00";
UPDATE `jobsinfo` SET `career_name`="Locomotive Firer" where id="53-4012.00";
UPDATE `jobsinfo` SET `career_name`="Rail Yard Engineer" where id="53-4013.00";
UPDATE `jobsinfo` SET `career_name`="Deck officer" where id="53-5021.02";
UPDATE `jobsinfo` SET `career_name`="Pharmacist" where id="29-1061.00";
UPDATE `jobsinfo` SET `career_name`="Art Therapist" where id="29-1125.01";
UPDATE `jobsinfo` SET `career_name`="Music Therapist" where id="29-1125.02";
UPDATE `jobsinfo` SET `career_name`="Dermatologist" where id="29-1069.02";
UPDATE `jobsinfo` SET `career_name`="General Practitioner" where id="29-1062.00";
UPDATE `jobsinfo` SET `career_name`="Gynecologist" where id="29-1064.00";
UPDATE `jobsinfo` SET `career_name`="Immunologist" where id="29-1069.01";
UPDATE `jobsinfo` SET `career_name`="Internist" where id="29-1063.00";
UPDATE `jobsinfo` SET `career_name`="Neurologist" where id="29-1069.04";
UPDATE `jobsinfo` SET `career_name`="Ophthalmologist" where id="29-1069.06";
UPDATE `jobsinfo` SET `career_name`="Forensic Pathologist" where id="29-1069.07";
UPDATE `jobsinfo` SET `career_name`="Pediatrician" where id="29-1065.00";
UPDATE `jobsinfo` SET `career_name`="Psychiatrist" where id="29-1066.00";
UPDATE `jobsinfo` SET `career_name`="Radiologist" where id="29-1069.10";
UPDATE `jobsinfo` SET `career_name`="Urologist" where id="29-1069.12";