UPDATE `personal_values` SET `name` = 'Achievement' WHERE `id` = '1';
UPDATE `personal_values` SET `name` = 'Altruism' WHERE `id` = '2';
UPDATE `personal_values` SET `name` = 'Authority' WHERE `id` = '3';
UPDATE `personal_values` SET `name` = 'Beauty' WHERE `id` = '4';
UPDATE `personal_values` SET `name` = 'Competence' WHERE `id` = '5';
UPDATE `personal_values` SET `name` = 'Concern for Enviorenment' WHERE `id` = '6';
UPDATE `personal_values` SET `name` = 'Creativity' WHERE `id` = '7';
UPDATE `personal_values` SET `name` = 'Curiosity' WHERE `id` = '8';
UPDATE `personal_values` SET `name` = 'Daring' WHERE `id` = '9';
UPDATE `personal_values` SET `name` = 'Devoutness' WHERE `id` = '10';
UPDATE `personal_values` SET `name` = 'Discipline' WHERE `id` = '11';
UPDATE `personal_values` SET `name` = 'Enjoying Life' WHERE `id` = '12';
UPDATE `personal_values` SET `name` = 'Equality' WHERE `id` = '13';
UPDATE `personal_values` SET `name` = 'Excitement' WHERE `id` = '14';
UPDATE `personal_values` SET `name` = 'Freedom' WHERE `id` = '15';
UPDATE `personal_values` SET `name` = 'Friendship' WHERE `id` = '16';
UPDATE `personal_values` SET `name` = 'Health' WHERE `id` = '17';
UPDATE `personal_values` SET `name` = 'Honesty' WHERE `id` = '18';
UPDATE `personal_values` SET `name` = 'Humility' WHERE `id` = '19';
UPDATE `personal_values` SET `name` = 'Independence' WHERE `id` = '20';
UPDATE `personal_values` SET `name` = 'Inner Harmony' WHERE `id` = '21';
UPDATE `personal_values` SET `name` = 'Intelligence' WHERE `id` = '22';
UPDATE `personal_values` SET `name` = 'Justice' WHERE `id` = '23';
UPDATE `personal_values` SET `name` = 'Love' WHERE `id` = '24';
UPDATE `personal_values` SET `name` = 'Loyalty' WHERE `id` = '25';
UPDATE `personal_values` SET `name` = 'Meaning in Life' WHERE `id` = '26';
UPDATE `personal_values` SET `name` = 'Open-mindedness' WHERE `id` = '27';
UPDATE `personal_values` SET `name` = 'Peace' WHERE `id` = '28';
UPDATE `personal_values` SET `name` = 'Politeness' WHERE `id` = '29';
UPDATE `personal_values` SET `name` = 'Privacy' WHERE `id` = '30';
UPDATE `personal_values` SET `name` = 'Recognition' WHERE `id` = '31';
UPDATE `personal_values` SET `name` = 'Responsibility' WHERE `id` = '32';
UPDATE `personal_values` SET `name` = 'Security' WHERE `id` = '33';
UPDATE `personal_values` SET `name` = 'Self-respect' WHERE `id` = '34';
UPDATE `personal_values` SET `name` = 'Sense of Belonging' WHERE `id` = '35';
UPDATE `personal_values` SET `name` = 'Spirituality' WHERE `id` = '36';
UPDATE `personal_values` SET `name` = 'Success' WHERE `id` = '37';
UPDATE `personal_values` SET `name` = 'Traditions' WHERE `id` = '38';
UPDATE `personal_values` SET `name` = 'Variety' WHERE `id` = '39';
UPDATE `personal_values` SET `name` = 'Wealth' WHERE `id` = '40';
UPDATE `personal_values` SET `name` = 'Wisdom' WHERE `id` = '41';